### PR TITLE
Memory info and more details in opentelemetry

### PR DESCRIPTION
**Pull request by mpardalos**
This patch adds the following information to opentelemetry traces:

* Number of entries in the "state" hashmap in ShakeExtras (Metric is called "values map size_bytes")
* Memory occupancy in that map. (This is currently very slow, and so sizes are only reported about once/minute)
* Trace of *all* LSP requests and notifications (as opposed to just those defined in HoverDefinition.hs, as before)

Other changes:
* Put opentelemetry tracing behind `--ot-profiling` flag
* Add flag to benchmark to run ghcide with `--ot-profiling`
* Improve recording of heap_live_bytes in opentelemetry trace by running performGC every 0.5s

Functionality is complete, ~but marking as draft because of the following dependency issues~ all these issues have been resolved so I've marked the PR as ready for review:
* [X] ~I am using a still-unpublished library ([heapsize](https://github.com/mpardalos/heapsize)). Waiting for my hackage account to be approved to upload this~ [heapsize](https://github.com/mpardalos/heapsize) is now [on hackage](https://hackage.haskell.org/package/heapsize)
* [X] ~I bumped opentelemetry to 0.6.0, which drops support for ghc 8.6. Waiting for [this PR](https://github.com/ethercrow/opentelemetry-haskell/pull/38) to be merged and the new version to be pushed to hackage.~ opentelemetry-0.6.1, supporting GHC 8.6 is on hackage.

~I'm not sure if I should rebase this patch/squash it down. @wz1000 what do you think?~ (Rebased it onto the top, merges fine now)

** GSoC project info

I am using this PR as a work product submission for my GSoC project. Information related to that here:

* This PR is a continuation of the work done [in this PR](https://github.com/mpickering/ghcide/pull/54)
* My work on ghcide also required changes to opentelemetry which were submitted in [this PR](https://github.com/ethercrow/opentelemetry-haskell/pull/34) and [this PR](https://github.com/ethercrow/opentelemetry-haskell/pull/35)
* The heapsize package I linked above is a fork of ghc-datasize that was needed to make this project feasible.
* While working on the heapsize package, I encountered a bug in GHC. The work done for that is outlined in [this blog post](https://mpickering.github.io/ide/posts/2020-08-04-measuring-memory-size.html)

CC: @mpickering @ethercrow

### CODE REVIEW

**Comment by pepeiborra** [comment]
What’s the status of this work?

**Comment by mpardalos** [comment]
The PR is ready to merge, and I'm waiting for any review comments, if there is any.

**Comment by wz1000** [comment]
Like I think I mentioned on IRC, you should open this against ghcide master.

**Comment by pepeiborra** [comment]
How can this PR be ready to be merge when it has >20 conflicts? 
Please rebase, fix the conflicts, send a PR against haskell/ghcide and then hopefully you will get feedback

**Comment by mpardalos** [comment]
Closing to reopen on haskell/ghcide

**Pull request closed without merging**
