### PR TITLE
Disable checkParents on open and close document

### PR DESCRIPTION
**Pull request by pepeiborra**

### CODE REVIEW

**Comment by wz1000** [comment]
Why? I think this is necessary at least on close, so that discarded modifications are propagated properly (i.e. the user closes a file without saving).

**Comment by pepeiborra** [comment]
It's not that it isn't worth doing, but that the configuration setting says the user doesn't want to do it. In a repo with 20000 modules, check parents can be very expensive.

**Comment by pepeiborra** [comment]
Bump

**Comment by wz1000** [comment]
Can we still check parents on close?

**Comment by pepeiborra** [comment]
> Can we still check parents on close?

I have added a new option for that. I wanted to extend the existing tests, but there are none!

**Pull request merged**
